services:
  db:
    container_name: lenpostgres
    image: pgvector/pgvector:pg18-trixie
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - "${DB_PORT:-5432}:5432"
    networks:
      - lojban-network
  redis:
    container_name: lenredis
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - lojban-network

networks:
  lojban-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
